# Generated by Django 6.0.4 on 2026-04-30 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0009_registro_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abono',
            name='tipo_registro',
        ),
        migrations.AddField(
            model_name='comprobante',
            name='tipo_registro',
            field=models.CharField(blank=True, choices=[('central_1', 'Central 1'), ('central_2', 'Central 2'), ('central_ia', 'Central IA'), ('seguimiento', 'Seguimiento')], help_text='Origen del registro: Central 1, Central 2, Central IA o Seguimiento.', max_length=20, null=True, verbose_name='Tipo de registro'),
        ),
        migrations.AlterField(
            model_name='abono',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='jornadacurso',
            name='ciudad',
            field=models.CharField(blank=True, help_text='Ciudad (presencial) o plataforma (online). Opcional.', max_length=100),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='jornada',
            field=models.ForeignKey(blank=True, help_text='Fecha y horario seleccionados (depende del curso y modalidad).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='academia.jornadacurso'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='valor_curso',
            field=models.DecimalField(decimal_places=2, help_text='Se autocompleta con el valor del curso según modalidad, pero puedes ajustarlo.', max_digits=10),
        ),
    ]
