# Generated by Django 6.0.4 on 2026-05-07 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0012_unificar_matricula_comprobante'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('retiro_voluntario', 'Retiro voluntario')], default='activa', help_text='Estado académico de la matrícula.', max_length=20),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='registrado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que registró la matrícula (admin o asesor). Se usa también como vendedor/a en el comprobante asociado.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matriculas_registradas', to=settings.AUTH_USER_MODEL),
        ),
    ]
