# Generated by Django 6.0.5 on 2026-05-09 02:07

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0013_matricula_estado_alter_matricula_registrado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='abono',
            name='cuenta_para_saldo',
            field=models.BooleanField(default=True, help_text='Si es FALSE, este pago NO suma al valor pagado del curso. Se usa cuando una clase de recuperación se cobra aparte.'),
        ),
        migrations.AddField(
            model_name='abono',
            name='numero_modulo',
            field=models.PositiveIntegerField(blank=True, help_text='Si el pago es por módulo o de recuperación, indica qué módulo cubre.', null=True),
        ),
        migrations.AddField(
            model_name='abono',
            name='tipo_pago',
            field=models.CharField(choices=[('abono', 'Abono'), ('pago_completo', 'Pago Completo'), ('por_modulo', 'Por Módulo'), ('recuperacion', 'Clase de Recuperación')], default='abono', help_text='Tipo de pago: abono libre, pago completo, por módulo o recuperación.', max_length=20),
        ),
        migrations.AddField(
            model_name='curso',
            name='numero_modulos',
            field=models.PositiveIntegerField(default=4, help_text='Cantidad de módulos del programa. Se usa para el control de pagos por módulo.'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Descuento aplicado al valor del curso (USD). Opcional.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='abono',
            name='fecha',
            field=models.DateField(help_text='Fecha en que se recibió el pago.'),
        ),
        migrations.AlterField(
            model_name='abono',
            name='monto',
            field=models.DecimalField(decimal_places=2, help_text='Cantidad recibida en este pago (USD).', max_digits=10),
        ),
        migrations.CreateModel(
            name='RecuperacionPendiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_modulo', models.PositiveIntegerField(help_text='Módulo de la clase que se debe recuperar.')),
                ('fecha_marcada', models.DateField(help_text='Fecha en que se marcó la clase a recuperar.')),
                ('saldo_pendiente_al_marcar', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Saldo que el estudiante tenía pendiente al momento de marcar la recuperación. Se arrastra para mostrarlo cuando se cobre la recuperación.', max_digits=10)),
                ('pagada', models.BooleanField(default=False, help_text='True cuando el estudiante ya recuperó la clase y se cobró.')),
                ('fecha_recuperacion', models.DateField(blank=True, help_text='Fecha en que efectivamente recuperó la clase.', null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('abono', models.OneToOneField(blank=True, help_text='Pago asociado a esta recuperación (si ya se cobró).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recuperacion', to='academia.abono')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recuperaciones_pendientes', to='academia.matricula')),
            ],
            options={
                'verbose_name': 'Clase en recuperación',
                'verbose_name_plural': 'Clases en recuperación',
                'ordering': ['pagada', '-fecha_marcada', '-creado'],
            },
        ),
    ]
