# Generated by Django 6.0.4 on 2026-05-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0015_alertapagorevisada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertapagorevisada',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
