# Generated by Django 6.0.5 on 2026-05-09 20:59

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0016_alter_alertapagorevisada_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonaExterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('apellidos', models.CharField(max_length=100)),
                ('nombres', models.CharField(max_length=100)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('celular', models.CharField(blank=True, max_length=20)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Persona externa',
                'verbose_name_plural': 'Personas externas',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='Adicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_adicional', models.CharField(choices=[('cert_matricula', 'Certificado de matrícula'), ('cert_asistencia', 'Certificado de asistencia'), ('cert_antiguo', 'Certificado antiguo'), ('examen_supletorio', 'Examen supletorio'), ('camisa', 'Camisa')], help_text='Tipo de servicio/producto adicional.', max_length=30)),
                ('modalidad', models.CharField(blank=True, choices=[('presencial', 'Presencial'), ('online', 'Online')], help_text='Modalidad del curso (presencial/online).', max_length=20)),
                ('talla_camiseta', models.CharField(blank=True, choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('NA', 'Ninguna de las anteriores (la academia solo cubre hasta XL)')], help_text='Solo aplica si tipo_adicional = camisa.', max_length=2)),
                ('numero_modulo', models.PositiveIntegerField(blank=True, help_text='Módulo del examen supletorio.', null=True)),
                ('fecha', models.DateField(help_text='Fecha en que se cobró el adicional.')),
                ('valor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor del adicional (USD). El usuario lo define libremente.', max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia bancaria'), ('tarjeta', 'Tarjeta de crédito/débito')], default='efectivo', help_text='Forma de pago.', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('curso', models.ForeignKey(blank=True, help_text='Curso al que se refiere el certificado o examen. No aplica para camisas.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adicionales', to='academia.curso')),
                ('estudiante', models.ForeignKey(blank=True, help_text='Estudiante interno de la academia.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adicionales', to='academia.estudiante')),
                ('matricula_origen', models.ForeignKey(blank=True, help_text='Matrícula desde la que se generó el examen supletorio (si se marcó desde el detalle de pagos).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adicionales_supletorios', to='academia.matricula')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adicionales_registrados', to=settings.AUTH_USER_MODEL)),
                ('persona_externa', models.ForeignKey(blank=True, help_text='Persona externa a la academia.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adicionales', to='academia.personaexterna')),
            ],
            options={
                'verbose_name': 'Adicional',
                'verbose_name_plural': 'Adicionales',
                'ordering': ['-fecha', '-creado'],
            },
        ),
    ]
