# Generated by Django 6.0.4 on 2026-05-09 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0017_personaexterna_adicional'),
    ]

    operations = [
        migrations.AddField(
            model_name='adicional',
            name='banco',
            field=models.CharField(blank=True, choices=[('pichincha', 'Banco Pichincha'), ('guayaquil', 'Banco Guayaquil'), ('produbanco', 'Produbanco'), ('pacifico', 'Banco Pacífico'), ('payphone', 'Payphone'), ('interbancaria', 'Interbancaria')], help_text='Banco usado (solo si el método es Transferencia bancaria o Tarjeta).', max_length=20),
        ),
        migrations.AddField(
            model_name='adicional',
            name='numero_recibo',
            field=models.CharField(blank=True, help_text='Número de comprobante. Si se deja vacío, se genera automáticamente.', max_length=30, unique=True),
        ),
    ]
